### ISSUE TITLE
Add MD5 check function 

### ISSUE THREAD

**Issue by MrTaco9001** [rojo-rbx/remodel#45]
I wrote a script that automatically creates parity between the build.rbxlx and the filesystem. That is to say that if I delete a file in Roblox then it is automatically deleted in the filesystem as-well and vise versa.

The primary issue here is that in order to delete files in the filesystem I have to use FindFirstChild which does not guarantee that the file it's trying to delete is the same as the model in the roblox file. A way around this would be a way to compare the MD5 of the rbxmx file and the actual model in-game.

**Comment by MrTaco9001** [comment]
![image](https://user-images.githubusercontent.com/22112182/115830027-b71a8300-a3dd-11eb-925d-abeed1f59db8.png)

For context: I want to replace `currentPath:FindFirstChild()` with `if currentPath:GetMD5(currentPath) == remodel:GetMD5(inst)`
Where `currentPath` is a Roblox instance and `inst` is a rbxmx file

**Comment by LPGhatguy** [comment]
MD5 is a specific, outdated, and insecure hash function. If we're going to add a hash function, it's not going to be MD5.

I'm not entirely sure how hashing actually fits in here. What are we hashing? In your problem, you mention hashing an rbxmx file and an instance. Are we hashing all of their properties, converted into some string form, concatenated together?

Overall, I think this is a good use case for a library. It might be possible to load existing Lua 5.3 C modules to accomplish what you're trying to do. Otherwise, a Lua implementation of a hash function is likely available and could probably be used.

**Comment by MrTaco9001** [comment]
Each instance has a built-in MD5 tag. I was merely suggesting we use that existing MD5 to insure parity between the file system and the place file.

**Comment by LPGhatguy** [comment]
Where is the built-in MD5 tag stored that you're mentioning? Files have `SharedString` values, which currently use MD5, but this is unrelated and also going to change to a different hash function eventually I think.

**Comment by MrTaco9001** [comment]
I remember reading close to the bottom of the files there's a string. It might be what you're referring to.
